config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    post 'subscribe', on: :member
    post 'unsubscribe', on: :member
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
  resources :comments, except: [:new] do
    resources :comments, only: [:new]
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author, :post, presence: true

  belongs_to :author,
    class_name: :User

  belongs_to :post

  has_many :comments,
  class_name: :Comment,
  foreign_key: :parent_comment_id,
  primary_key: :id

  belongs_to :parent_comment,
    class_name: :Comment

  has_many :votes, as: :votable

  def vote_count
    self.votes.inject(0) { |acc, vote| acc + vote.value }
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:show, :destroy, :upvote, :downvote]

  def upvote
    @comment.votes.new(value: 1)
    save(@comment)
  end

  def downvote
    @comment.votes.new(value: -1)
    save(@comment)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def destroy
    if @comment.destroy
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :show
    end
  end

  def show

  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def owner
    unless @comment.author == current_user
      flash[:errors] = ["You don't have permission to do that."]
      redirect_to post_url(@comment.post)
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="well well-sm">
  <div class="title_container">
    <div style="margin-right: 15px;">
      <form action="<%= upvote_comment_url(comment) %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button type="submit" class="btn btn-sm btn-success">
          <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
        </button>
      </form>

      <form action="<%= downvote_comment_url(comment) %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button type="submit" class="btn btn-sm btn-danger">
          <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
        </button>
      </form>
    </div>
    <div class="">
      (<%= comment.vote_count %>) <%= "#{comment.author.username}: #{comment.content} - #{comment.created_at.strftime("%D at %I:%M%p")}" %>
      <%= render "comments/form", url: comments_url, method: "post", post_id: comment.post_id, parent_comment_id: comment.id, comment: Comment.new %>
    </div>

  </div>


<button type="button" name="button" class="comment-collapse">Collapse</button>
<ul>
  <% comment.comments.sort{ |a,b| b.created_at <=> a.created_at }.each do |c| %>
    <%= render "comments/comment", comment: c %>
  <% end %>
</ul>
</div>

app/views/comments/_form.html.erb
<form action="<%= url %>" method="post" class="form-inline">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">
  <textarea class="form-control" name="comment[content]" rows="1" cols="40"><%= comment.content %></textarea>
  <input type="hidden" name="comment[post_id]" value="<%= post_id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= parent_comment_id %>">
  <input type="submit" class="btn btn-success" value="Comment">
</form>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render "form", url: comments_url, method: "post", post_id: params[:post_id], parent_comment_id: params[:comment_id], comment: @comment %>