config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    post 'subscribe', on: :member
    post 'unsubscribe', on: :member
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
  resources :comments, except: [:new] do
    resources :comments, only: [:new]
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if params[:search]
      case params[:type]
      when "posts"
        @title = "Searched Posts"
        @posts = Post.where("lower(title) LIKE '%#{params[:search].downcase}%' OR lower(content) LIKE '%#{params[:search].downcase}%'")
      when "subs"
        @title = "Searched Subreddits"
        @subs = Sub.where("lower(title) LIKE '%#{params[:search].downcase}%' OR lower(description) LIKE '%#{params[:search].downcase}%'")
      end
      return
    end
    if current_user
      posts = current_user.subbed_posts
    else
      posts = Post.all
    end
    @title = "Subscribed Posts"
    @posts = posts.sort{ |a,b| b.vote_count <=> a.vote_count }
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1><%= @title %></h1>

<% if @posts %>
  <% @posts.each do |post| %>
    <div class="title_container">
      <div style="background-image: url(<%= post.url %>); width: 50px; height: 50px;"></div>
      <div style="margin-right: 15px; margin-left: 15px;">
        <form action="<%= upvote_post_url(post) %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
          </button>
        </form>

        <form action="<%= downvote_post_url(post) %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <button type="submit" class="btn btn-danger">
            <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
          </button>
        </form>
      </div>
      <div>
        <h1><%= link_to " (#{post.vote_count}) #{post.title}", post_url(post) %></h1>
        <h4><%= link_to post.url, post.url %></h4>
      </div>
    </div>

  <% end %>
<% end %>

<% if @subs %>
  <% @subs.each do |sub| %>
    <div class="title_container">
      <div>
        <h1><%= link_to sub.title, sub_url(sub) %></h1>
        <h4><%= sub.description %></h4>
      </div>
    </div>
  <% end %>
<% end %>