config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    post 'subscribe', on: :member
    post 'unsubscribe', on: :member
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
  resources :comments, except: [:new] do
    resources :comments, only: [:new]
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator, presence: true

  has_many :post_subs, dependent: :destroy
  has_many :posts, through: :post_subs, dependent: :destroy

  has_many :subscribers,
    foreign_key: :user_id,
    class_name: :User

  belongs_to :moderator,
    class_name: :User,
    dependent: :destroy
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :authenticate, except: [:index, :show]
  before_action :find_sub, only: [:edit, :update, :destroy, :show, :subscribe, :unsubscribe]
  before_action :owner, only: [:edit, :update, :destroy]

  def subscribe
    new_sub = Subscription.new
    new_sub.user = current_user
    new_sub.sub = @sub
    if new_sub.save
      redirect_to :back
    else
      flash[:error] = new_sub.errors.full_messages
      redirect_to :back
    end
  end

  def unsubscribe
    sub = Subscription.find_by(user: current_user, sub: @sub)
    if sub.destroy
      redirect_to :back
    else
      flash[:error] = sub.errors.full_messages
      redirect_to :back
    end
  end

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @sub.destroy
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      redirect_to sub_url(@sub)
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def find_sub
    @sub = Sub.find(params[:id])
  end

  def owner
    unless @sub.moderator == current_user
      flash[:errors] = ["You don't have permission to do that."]
      redirect_to sub_url(@sub)
    end
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<%= quick_form url: url, method: method do %>
  <label>
    Title
    <input type="text" name="sub[title]" value="<%= sub.title %>">
  </label>
  <label>
    Description
    <textarea name="sub[description]" rows="8" cols="40"><%= sub.description %></textarea>
  </label>
<% end %>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<%= render 'form', sub: @sub, method: "patch", url: sub_url(@sub) %>

app/views/subs/index.html.erb
<table class="table">
  <thead>
    <th>Title</th>
    <th>Description</th>
  </thead>
  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td><%= link_to sub.title, sub_url(sub) %></td>
        <td><%= sub.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Create Sub", new_sub_url, class: "btn btn-success" %>

app/views/subs/new.html.erb
<h1>Create New Sub</h1>
<%= render 'form', sub: @sub, method: "post", url: subs_url %>

app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>
<p><%= @sub.description %></p>

<% if current_user.subscriptions.include?(@sub) %>
  <%= button_to "Unsubscribe", unsubscribe_sub_url(@sub) %>
<% else %>
  <%= button_to "Subscribe", subscribe_sub_url(@sub) %>
<% end %>

<a href="<%= subs_url %>" class="btn btn-primary">
  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> All Subs
</a>
<hr>

<h4>Posts</h4>
<% @sub.posts.each do |post| %>
  <%= link_to "(#{post.vote_count}) #{post.title}", post_url(post) %>
<% end %>
<hr>
<%= link_to "New Post", new_post_url, class: "btn btn-success" %>