config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    post 'subscribe', on: :member
    post 'unsubscribe', on: :member
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
  resources :comments, except: [:new] do
    resources :comments, only: [:new]
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author, presence: true
  validates :subs, length: { minimum: 1 }

  belongs_to :author,
    class_name: :User

  has_many :post_subs, dependent: :destroy

  has_many :subs, through: :post_subs

  has_many :votes, as: :votable

  # has_many :comments

  def comments
    c = Comment.includes(:comments, :author).order("created_at DESC").joins(:post).where(post_id: self.id).order("created_at DESC")
    c.select { |comment| comment.parent_comment_id.nil? }
  end

  def vote_count
    self.votes.inject(0) { |acc, vote| acc + vote.value }
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate, except: [:show]
  before_action :find_post, only: [:edit, :update, :destroy, :show, :upvote, :downvote]
  before_action :owner, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def upvote
    vote = Vote.find_by(votable: @post, user_id: current_user.id)
    if vote && vote.value == 1
      flash[:errors] = ["You can't upvote twice!"]
      redirect_to :back
    else
      if vote
        vote.value = 1
      else
        vote = @post.votes.new(value: 1)
        vote.user = current_user
      end
      save(vote)
    end
  end
  def downvote
    vote = Vote.find_by(votable: @post, user_id: current_user.id)
    if vote && vote.value == -1
      flash[:errors] = ["You can't downvote twice!"]
      redirect_to :back
    else
      if vote
        vote.value = -1
      else
        vote = @post.votes.new(value: -1)
        vote.user = current_user
      end
      save(vote)
    end
  end

  def edit
  end

  def show
  end

  def update
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to sub_url(@post.sub)
    else
      flash.now[:errors] = @post.errors.full_messages
      redirect_to post_url(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def owner
    unless @post.author == current_user
      flash[:errors] = ["You don't have permission to do that."]
      redirect_to sub_url(@post.sub)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= quick_form url: url, method: method do %>
  <label>
    Title
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <label>
    URL
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  <label>
    Content
    <textarea name="post[content]" rows="8" cols="40"><%= post.content %></textarea>
  </label>
  <label>
    Subs
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
      <label>
        <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if post.sub_ids.include?(sub.id) %>>
        <%= sub.title %>
      </label>
    <% end %>
  </label>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form', post: @post, url: post_url(@post), method: "patch" %>

app/views/posts/new.html.erb
<h1>Create New Post</h1>
<%= render 'form', post: @post, url: posts_url, method: "post" %>

app/views/posts/show.html.erb
<div class="title_container">
  <div style="margin-right: 15px;">
    <form action="<%= upvote_post_url(@post) %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
      </button>
    </form>

    <form action="<%= downvote_post_url(@post) %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <button type="submit" class="btn btn-danger">
        <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
      </button>
    </form>
  </div>
  <div>
    <h1><%= " (#{@post.vote_count}) #{@post.title}" %></h1>
    <h4><%= link_to @post.url, "http://" + @post.url %></h4>
  </div>
</div>

<p><%= @post.content %></p>

<% if current_user == @post.author %>
  <%= link_to "Edit Post", edit_post_url(@post), class: "btn btn-info" %>
<% end %>
<%= render "comments/form", url: comments_url, method: "post", post_id: @post.id, comment: Comment.new, parent_comment_id: nil %>
<hr>
<h4>Comments</h4>
<% @post.comments.each do |comment| %>
  <%= render "comments/comment", comment: comment %>
<% end %>